version: 0.2

phases:
  install:
    commands:
      - sudo yum install -y yum-utils shadow-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform

  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init

  build:
    commands:
      - bash tf_schedule.sh

  post_build:
    commands:
      - echo "Terraform deployment completed on `date`"
      - echo "Cleaning up..."
      - rm -f tfplan

artifacts:
  files:
    - '**/*'