---
version: 0.2
phases:
  install:
    commands:
      - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee
        /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg]
        https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee
        /etc/apt/sources.list.d/hashicorp.list
      - apt update && apt install -y terraform
  pre_build:
    commands:
      - terraform init
  build:
    commands:
      - terraform destroy -auto-approve
  post_build:
    commands:
      - echo "Cleaning up..."
      - rm -f tfplan
